version: '3.8'

services:
  latex:
    build: .
    volumes:
      - .:/workspace
    command: ["sh", "-c", "lualatex --shell-escape --interaction=nonstopmode budavariam.tex && lualatex --shell-escape --interaction=nonstopmode budavariam.tex"]